import React from 'react';
import EtatDePaiementTable from './EtatDePaiementParSite';

const data = [
  {
    site: 'AKOA HOTEL RESTAURANT',
    delegations: [
      { name: 'Nombre de Lit', nombrePersonnes: 14 },
      { name: 'Nombre de Pax', nombrePersonnes: 24 },
      { name: 'Nombre de séjours', nombrePersonnes: 16 },
      { name: 'Coût Proformat (Ariary)', nombrePersonnes: 41808000 },
      { name: 'Coût Facture (Ariary)', nombrePersonnes: 41808000 },
      { name: 'Premier accompte (35%)', nombrePersonnes: 14632800},
      { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'oui' },
      { name: 'Deuxième accompte (35%)', nombrePersonnes: 14632800 },
      { name: 'Reste (30%)', nombrePersonnes: 12542400 },

      // Ajoutez les délégations pour le site Radisson ici
    ],
  },
  { site: 'ANALAMANGA PARK', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 70 },
      { name: 'Nombre de Pax', nombrePersonnes: 70 },
      { name: 'Nombre de séjours', nombrePersonnes: 15 },
      { name: 'Coût Proformat', nombrePersonnes: 30200000 },
      { name: 'Coût Facture', nombrePersonnes: 30200000 },
      { name: 'Premier accompte (35%)', nombrePersonnes: 10570000 },
      { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'Non' },
      { name: 'Deuxième accompte (35%)', nombrePersonnes: 10570000 },
      { name: 'Reste (30%)', nombrePersonnes: 0 },
  ] },
  { site: 'ANJARY HOTEL', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 125 },
      { name: 'Nombre de Pax', nombrePersonnes: 162 },
      { name: 'Nombre de séjours', nombrePersonnes: 17 },
      { name: 'Coût Proformat', nombrePersonnes: 208573000 },
      { name: 'Coût Facture', nombrePersonnes: 208573000 },
      { name: 'Premier accompte (35%)', nombrePersonnes: 73000550 },
      { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'Oui' },
      { name: 'Deuxième accompte (35%)', nombrePersonnes: 73000550 },
      { name: 'Reste (30%)', nombrePersonnes: 62571900 },
  ] },
  { site: 'ANOUK HOTEL', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 18 },
  { name: 'Nombre de Pax', nombrePersonnes: 18 },
  { name: 'Nombre de séjours', nombrePersonnes: 16 },
  { name: 'Coût Proformat', nombrePersonnes: 34320000 },
  { name: 'Coût Facture', nombrePersonnes: 34320000 },
  { name: 'Premier accompte (35%)', nombrePersonnes: 12012000 },
  { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'Non' },
  { name: 'Deuxième accompte (35%)', nombrePersonnes: 12012000 },
  { name: 'Reste (30%)', nombrePersonnes: 10296000 },] },

  { site: 'ARISOA HOTEL', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 21 },
  { name: 'Nombre de Pax', nombrePersonnes: 21 },
  { name: 'Nombre de séjours', nombrePersonnes: 16 },
  { name: 'Coût Proformat', nombrePersonnes: 84880000 },
  { name: 'Coût Facture', nombrePersonnes: 84880000 },
  { name: 'Premier accompte (35%)', nombrePersonnes: 29708000 },
  { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'Non' },
  { name: 'Deuxième accompte (35%)', nombrePersonnes: 29708000 },
  { name: 'Reste (30%)', nombrePersonnes: 25464000 },
  ] },

  { site: 'ASIA & AFRICA', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 50 },
  { name: 'Nombre de Pax', nombrePersonnes: 46 },
  { name: 'Nombre de séjours', nombrePersonnes: 14 },
  { name: 'Coût Proformat', nombrePersonnes: 130208000 },
  { name: 'Coût Facture', nombrePersonnes: 68965000 },
  { name: 'Premier accompte (35%)', nombrePersonnes: 24137750 },
  { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'oui' },
  { name: 'Deuxième accompte (35%)', nombrePersonnes: 24137750 },
  { name: 'Reste (30%)', nombrePersonnes: 20689500 },
  ] },
  { site: 'ASTAURIA', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 41 },
  { name: 'Nombre de Pax', nombrePersonnes: 41 },
  { name: 'Nombre de séjours', nombrePersonnes: 16 },
  { name: 'Coût Proformat', nombrePersonnes: 24000000 },
  { name: 'Coût Facture', nombrePersonnes: 24000000 },
  { name: 'Premier accompte (35%)', nombrePersonnes: 8400000 },
  { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'oui' },
  { name: 'Deuxième accompte (35%)', nombrePersonnes: 8400000 },
  { name: 'Reste (30%)', nombrePersonnes: 7200000 },
  ] },
  { site: 'ATHANA EVENT HOTEL', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 32 },
  { name: 'Nombre de Pax', nombrePersonnes: 32 },
  { name: 'Nombre de séjours', nombrePersonnes: 16 },
  { name: 'Coût Proformat', nombrePersonnes: 55200000 },
  { name: 'Coût Facture', nombrePersonnes: 55200000 },
  { name: 'Premier accompte (35%)', nombrePersonnes: 19320000 },
  { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'oui' },
  { name: 'Deuxième accompte (35%)', nombrePersonnes: 19320000 },
  { name: 'Reste (30%)', nombrePersonnes: 16560000 },
  ] },
  { site: 'ATMO', delegations: [
    { name: 'Nombre de Lit', nombrePersonnes: 43 },
  { name: 'Nombre de Pax', nombrePersonnes: 55 },
  { name: 'Nombre de séjours', nombrePersonnes: 15 },
  { name: 'Coût Proformat', nombrePersonnes: 34320000 },
  { name: 'Coût Facture', nombrePersonnes: 34320000 },
  { name: 'Premier accompte (35%)', nombrePersonnes: 12012000 },
  { name: 'Réalisé (Oui/Non)', nombrePersonnes: 'Non' },
  { name: 'Deuxième accompte (35%)', nombrePersonnes: 12012000 },
  { name: 'Reste (30%)', nombrePersonnes: 10296000 },
  ] },
  { site: 'BIG BANG', delegations: [] },
  { site: 'CALLISTEMON', delegations: [] },
  { site: 'CARLTON', delegations: [] },
  { site: 'CASTELLO MOTEL', delegations: [] },
  { site: 'CENTRAL HOTEL', delegations: [] },
  { site: 'COMPLEXE CNAPS', delegations: [] },
  { site: 'ESPACE & HOTEL DESTINY', delegations: [] },
  { site: 'FEIMA HOTEL', delegations: [] },
  { site: 'FLORA HOTEL', delegations: [] },
  { site: 'GASSY COUNTRY HOUSE', delegations: [] },
  { site: 'GRACE HOUSE HOTEL', delegations: [] },
  { site: 'HANITRIARIVO', delegations: [] },
  { site: 'HAVANA Ressort & Spa', delegations: [] },
  { site: 'HOSTEL DU PERE PEDRO', delegations: [] },
  { site: 'HOTEL 15 HEURES', delegations: [] },
  { site: 'HOTEL BEL\'AIR', delegations: [] },
  { site: 'HOTEL COLBERT', delegations: [] },
  { site: 'HOTEL DES CYGNES', delegations: [] },
  { site: 'HOTEL FANANTENANA', delegations: [] },
  { site: 'HOTEL GREGOIRE', delegations: [] },
  { site: 'HOTEL LE VANILLIER', delegations: [] },
  { site: 'HOTEL SAINT PIERRE', delegations: [] },
  { site: 'HOTEL THREE "T" Bypass', delegations: [] },
  { site: 'HOTEL VAHINY', delegations: [] },
  { site: 'HUMAN HOTEL', delegations: [] },
  { site: 'IARIMBATO HOTEL', delegations: [] },
  { site: 'IBIS', delegations: [] },
  { site: 'ILO HOTEL', delegations: [] },
  { site: 'IRA', delegations: [] },
  { site: 'IVOTEL', delegations: [] },
  { site: 'KARIBOTEL', delegations: [] },
  { site: 'LA CASA DI LUNA', delegations: [] },
  { site: 'LA VILLETTE', delegations: [] },
  { site: 'L\'APPART', delegations: [] },
  { site: 'LE CARAT', delegations: [] },
  { site: 'LE CENTELL', delegations: [] },
  { site: 'LE CHÂTEAU D\'AMBOHIMALAZA', delegations: [] },
  { site: 'LE FRED', delegations: [] },
  { site: 'LE GRAND MELLIS', delegations: [] },
  { site: 'LE HINTSY', delegations: [] },
  { site: 'LE LOUVRE', delegations: [] },
  { site: 'LE MIRADOR', delegations: [] },
  { site: 'LE PAVE', delegations: [] },
  { site: 'LE RELAIS NORMAND', delegations: [] },
  { site: 'LE RIAD MEDINA TANA', delegations: [] },
  { site: 'LIVE HOTEL', delegations: [] },
  { site: 'MAHAVELO', delegations: [] },
  { site: 'MIA DOLCE VITA (SOA&CO)', delegations: [] },
  { site: 'NOVA HOTEL', delegations: [] },
  { site: 'NOVOTEL', delegations: [] },
  { site: 'NOTRE DAME DE CENACLE AMBOHIPO', delegations: [] },
  { site: 'ORCHID HOTEL', delegations: [] },
  { site: 'PALISSANDRE', delegations: [] },
  { site: 'PANORAMA', delegations: [] },
  { site: 'PAON D\'OR', delegations: [] },
  { site: 'PINAH HOTEL', delegations: [] },
  { site: 'PRADEY', delegations: [] },
  { site: 'RADAMA HOTEL', delegations: [] },
  { site: 'RADISSON APART', delegations: [] },
  { site: 'RADISSON BLU', delegations: [] },
  { site: 'RADISSON WATERFRONT', delegations: [] },
  { site: 'RELAIS DE LA HAUTE VILLE', delegations: [] },
  { site: 'RELAIS DES PLATEAUX', delegations: [] },
  { site: 'SAKAY ROUGE', delegations: [] },
  { site: 'SOLE HOTEL', delegations: [] },
  { site: 'SKY BLUE', delegations: [] },
  { site: 'SOOATEL', delegations: [] },
  { site: 'SUITES AUX CHARMES (VIP)', delegations: [] },
  { site: 'SUNNY GARDEN', delegations: [] },
  { site: 'TANA HOTEL', delegations: [] },
  { site: 'TINET LODGE', delegations: [] },
  { site: 'TOMETAL', delegations: [] },
  { site: 'TROPIC ASIA MADA', delegations: [] },
  { site: 'VALIHA HOTEL', delegations: [] },
  { site: 'WHITE PALACE', delegations: [] },


];

const EtatDePaiementParent = () => {
  return (
    <div>
      {/* Affichez d'autres composants ici si nécessaire */}
      <EtatDePaiementTable data={data} />
    </div>
  );
};

export default EtatDePaiementParent;
